# Generated by Django 4.1.6 on 2023-05-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
    ]
