# Generated by Django 4.1.6 on 2023-04-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cat_remove_news_category_news_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.AddField(
            model_name='news',
            name='Categories',
            field=models.ManyToManyField(to='main.categories'),
        ),
    ]
