# Generated by Django 4.1.6 on 2023-04-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_categories_remove_news_category_delete_cat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='Categories',
            new_name='categories',
        ),
    ]
